export const DEPARTMENTS = [
  { value: "Arts & Humanities", label: "Arts / Humanities" },
  { value: "Science", label: "Science" },
  { value: "Commerce & Management", label: "Commerce & Management" },
  { value: "Computer & IT", label: "Computer & IT" },
  { value: "Engineering", label: "Engineering" },
  { value: "Medical & Health Sciences", label: "Medical & Health Sciences" },
  { value: "Law", label: "Law" },
  { value: "Design & Creative Fields", label: "Design & Creative Fields" },
  { value: "Hotel Management & Tourism", label: "Hotel Management & Tourism" },
  { value: "Education", label: "Education" },
  { value: "Interdisciplinary / Emerging", label: "Interdisciplinary / Emerging" },
];

export const UG_COURSES = [
  "BA",
  "B.Sc",
  "B.Com",
  "BBA",
  "BMS",
  "BCA",
  "B.Sc IT",
  "B.Tech / B.E",
  "MBBS",
  "BDS",
  "B.Pharm",
  "B.Sc Nursing",
  "BPT",
  "BAMS / BHMS / BNYS",
  "LLB",
  "BA LLB / BBA LLB",
  "B.Des",
  "BFA",
  "Animation & VFX",
  "BHM",
  "BTTM",
  "B.Ed",
];

export const PG_COURSES = [
  "MA",
  "M.Sc",
  "M.Com",
  "MBA",
  "MCA",
  "M.Tech / ME",
  "MD",
  "MS",
  "MDS",
  "LLM",
  "M.Des",
  "M.Ed",
];

